version: '3.8'

services:
  ilya-db:
    container_name: ilya-db
    image: postgres:15
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
      POSTGRES_DB: master
    ports:
      - "3015:5432"
    volumes:
      - ilya-db-vol:/var/lib/postgresql/data



volumes:
  ilya-db-vol:
