version: '3.9'

services:
  auth:
    container_name: auth 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"  # Можно поменять 8000 на 8001, если уже занят
    depends_on:
      - auth-db
    networks:
      - auth_net
    environment:
      - DATABASE_URL=postgres://master:master@auth-db:5432/master
      - JWT_SECRET=${JWT_SECRET}

  auth-db:
    container_name: auth-db
    image: postgres:15
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
      POSTGRES_DB: master
    ports:
      - "5432:5432"  # Если уже занят, можно поменять на "5433:5432"
    volumes:
      - auth-db-vol:/var/lib/postgresql/data
    networks:
      - auth_net

volumes:
  auth-db-vol:

networks:
  auth_net:
    driver: bridge
